### ISSUE TITLE
Ver. 0.9.4 not able to retrieve data from URL when using Mega.nz link

### ISSUE THREAD

**Issue by rjbprime** [ptrsuder/cloud-folder-browser#11]
Hi @ptrsuder,

Trying to use ver.0.9.4 to grab some files from [this](https://mega.nz/folder/RNVxgSwZ#xMjHKmteBTsDJbm7TRKWvA) or [this](https://mega.nz/folder/MV021KiT#XbChaFK6_AiYqcc3_qjCDw)link, and I'm getting a "cannot retrieve data from URL" error.

What could be causing it? Has Mega.nz changed it's URL format or API?

**Comment by rjbprime** [comment]
Looking at another Mega.nz downloader, their users says that it seems that Mega.nz **has** changed their URL. The changes to folder links to get it to work with ver. 0.9.4 of your app is (before pasting the link into URL section) to replace the ```#``` in the middle of the URL with an ```!```, and ```/folder/``` section of the URL with ```/#F!```.

To apply this to allow for users to just input the links directly into your app, is to update the code to accept ```mega.nz/folder/(folder_link)#(decryption_key)```.

I'm not sure how this would be coded in your app, but I hope this helps.

**Comment by ptrsuder** [comment]
Oh yeah, they changed it. I'll make updates.

**Comment by ptrsuder** [comment]
Updated in https://github.com/ptrsuder/cloud-folder-browser/commit/6a0ddb0d02734c17602e53a85e4422ecc6681b3f
