### ISSUE TITLE
Sugestion: Download from Allsync folders

### ISSUE THREAD

**Issue by rjbprime** [ptrsuder/cloud-folder-browser#12]
Hi @ptrsuder,

Would it be possible to code in a downloader for Allsync.com folders? I am able to access password protected folders from cloud-folder-browser and create a link container file for jDownloader, but jDownloader is unable to download from those folders, even when supplying a download password.

**Comment by ptrsuder** [comment]
Oh, I didn't even think about this problem. 
Sure, will try to make it work.

**Comment by ptrsuder** [comment]
Should work with new release.

**Comment by rjbprime** [comment]
Using version 0.9.6, it downloads a 0 byte file based on the selected files.

**Comment by ptrsuder** [comment]
Maybe you loaded folder from file?

**Comment by rjbprime** [comment]
Not sure. I selected around 7000 files from two different shares in different directories, all PDFs, ZIPS, etc, are 0 bytes. After downloading, I closed the app, went into the folder, then selected the properties tab in explorer, and checked the file size and amount. correct amount of files, but the folder read 0 bytes.

The download for the files in this case was about 30 seconds, when the app said it should have been about 103gb.

**Comment by ptrsuder** [comment]
Load from link and try to download like... a few files?

**Comment by rjbprime** [comment]
Tried downloading a batch of 32 files, the app creates 32 files of 0 bytes. Thoughts?

**Comment by ptrsuder** [comment]
Okay, this is error with url string encoding again.

**Comment by ptrsuder** [comment]
Try new release.

**Comment by rjbprime** [comment]
0 Byte files and back to being limited to 4 downloads again. Thoughts?

**Comment by ptrsuder** [comment]
Ugh. Can you contact me with email, please? honheim@yandex.com
