### ISSUE TITLE
Cannot retrieve data from URL

### ISSUE THREAD

**Issue by czer0** [ptrsuder/cloud-folder-browser#14]
Certain Mega folders when attempting to connect will give "Cannot retrieve data from URL" error, can access these folders from a web browser.
Error started on around the 20th of May using release 0.9.5 and issue carried over into 0.9.6. previous these folders were accessible via cloud-folder-browser.
![error](https://user-images.githubusercontent.com/7904916/82851221-85e7b900-9ed5-11ea-89c5-ca579a24c950.png)

**Comment by ptrsuder** [comment]
It's probably for subfolders?

**Comment by czer0** [comment]
Although this does not explain why a working mega would suddenly stop working over the course of 24 hours.

**Comment by ptrsuder** [comment]
They are working... It's because or url structure changes, I didn't test my fix for 0.9.5 with subfolders at the time.

**Comment by czer0** [comment]
Is there a timeline for a fix?

**Comment by ptrsuder** [comment]
Try new release.

**Comment by czer0** [comment]
Sadly, issue is still present in v0.9.7

**Comment by ptrsuder** [comment]
Give me problematic link then.

**Comment by czer0** [comment]
Issue is resolved as of 0.9.8.
Great work, this is an awesome project.
Keep up the excellent work.
