### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by schena** [ptrsuder/cloud-folder-browser#15]
![image](https://user-images.githubusercontent.com/33556238/83148835-cca10300-a0cf-11ea-9052-cd7d2856a325.png)
I don't know why this error happens. windows 10 running as administrator.

**Comment by schena** [comment]
Consulte o final desta mensagem para obter detalhes sobre como chamar a 
depuração just-in-time (JIT) em vez desta caixa de diálogo.

************** Texto de Exceção **************
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em CloudFolderBrowser.MainForm.ParseTheTroveFolder(CloudFolder folder, String path) na E:\Documents\GitHub\cloud-folder-browser\CloudFolderBrowser\MainForm.cs:linha 692
   em CloudFolderBrowser.MainForm.Load_TheTrove(String url) na E:\Documents\GitHub\cloud-folder-browser\CloudFolderBrowser\MainForm.cs:linha 663
   em CloudFolderBrowser.MainForm.LoadPublicFolderKey_button_Click(Object sender, EventArgs e) na E:\Documents\GitHub\cloud-folder-browser\CloudFolderBrowser\MainForm.cs:linha 1309
   em System.Windows.Forms.Control.OnClick(EventArgs e)
   em System.Windows.Forms.Button.OnClick(EventArgs e)
   em System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   em System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.ButtonBase.WndProc(Message& m)
   em System.Windows.Forms.Button.WndProc(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   em System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Assemblies Carregados **************
mscorlib
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.4180.0 built by: NET48REL1LAST_B
    Base de Código: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
CloudFolderBrowser
    Versão do Assembly: 1.0.0.0
    Versão do Win32: 1.0.0.0
    Base de Código: file:///C:/Users/schen/Downloads/CloudFolderBrowser-0.9.1/CloudFolderBrowser.exe
----------------------------------------
System.Windows.Forms
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.4150.0 built by: NET48REL1LAST_C
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.4001.0 built by: NET48REL1LAST_C
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json
    Versão do Assembly: 12.0.0.0
    Versão do Win32: 12.0.1.22727
    Base de Código: file:///C:/Users/schen/Downloads/CloudFolderBrowser-0.9.1/Newtonsoft.Json.DLL
----------------------------------------
Aga.Controls
    Versão do Assembly: 1.7.6.0
    Versão do Win32: 1.7.6.0
    Base de Código: file:///C:/Users/schen/Downloads/CloudFolderBrowser-0.9.1/Aga.Controls.DLL
----------------------------------------
YandexDiskSharp
    Versão do Assembly: 1.0.0.0
    Versão do Win32: 1.0.0.0
    Base de Código: file:///C:/Users/schen/Downloads/CloudFolderBrowser-0.9.1/YandexDiskSharp.DLL
----------------------------------------
System.Configuration
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.4180.0 built by: NET48REL1LAST_B
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
PortableSettingsProvider
    Versão do Assembly: 0.2.1.0
    Versão do Win32: 0.2.1.0
    Base de Código: file:///C:/Users/schen/Downloads/CloudFolderBrowser-0.9.1/PortableSettingsProvider.DLL
----------------------------------------
System.Xml.Linq
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Accessibility
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Runtime.Serialization
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.4180.0 built by: NET48REL1LAST_B
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Numerics
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.4121.0 built by: NET48REL1LAST_C
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
HtmlAgilityPack
    Versão do Assembly: 1.8.6.0
    Versão do Win32: 1.8.6
    Base de Código: file:///C:/Users/schen/Downloads/CloudFolderBrowser-0.9.1/HtmlAgilityPack.DLL
----------------------------------------
System.Web
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.4075.0 built by: NET48REL1LAST
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
mscorlib.resources
    Versão do Assembly: 4.0.0.0
    Versão do Win32: 4.8.3752.0 built by: NET48REL1
    Base de Código: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_pt-BR_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Depuração JIT **************
Para habilitar a depuração just-in-time (JIT), o arquivo .config deste
aplicativo ou computador (machine.config) deve ter o valor
jitDebugging definido na seção system.windows.forms.
O aplicativo também deve ser compilado com a depuração
habilitada.

Por exemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando a depuração JIT está habilitada, qualquer exceção sem tratamento
será enviada ao depurador JIT registrado no computador,
em vez de ser tratada nesta caixa de diálogo.

**Comment by ptrsuder** [comment]
1. You need to use link for folder, not for whole site.
2. Don't use links for super big folders (like "/Books")
