### ISSUE TITLE
TheTrove retrieval seems to be broken again

### ISSUE THREAD

**Issue by ImportTaste** [ptrsuder/cloud-folder-browser#22]
During the retrieval, after a while, eventually an error pops up about a 404. You have the option to quit or continue, but unfortunately, I think the error halts the loading process regardless.

What's probably happening is that one of the links on TheTrove's directory is broken and the program doesn't have any way of handling that.

**Comment by ptrsuder** [comment]
What url are you trying to load?

**Comment by ImportTaste** [comment]
`https://thetrove.is/Browse/`

**Comment by ptrsuder** [comment]
You need to select more specific subfolder, because with this you are trying to load the whole site. Even something like main DnD folder is huge and will take noticeable time to load.

**Comment by ImportTaste** [comment]
Is that necessarily related to a 404 breaking the loading process, though?

**Comment by ptrsuder** [comment]
Okay, I should have fixed other issues and added error log window. Let me know if something is wrong!
