### ISSUE TITLE
# not encoded in URLs sent to JDownloader

### ISSUE THREAD

**Issue by ImportTaste** [ptrsuder/cloud-folder-browser#23]
I created a JDownloader linkcontainer and unfortunately, any link with a `#` in it 404s. These should be changed to `%23` to get the URLs to resolve correctly.

**Comment by ptrsuder** [comment]
Can you give me link for such file? Finding it for testing purposes is hard lol

**Comment by ImportTaste** [comment]
https://thetrove.is/Assets/3D/Papercraft/Fat%20Dragon%20Games/

**Comment by ImportTaste** [comment]
In case it matters, I've seen directories have it in their names too.
