### ISSUE TITLE
Fails to parse pages with question mark in the URL

### ISSUE THREAD

**Issue by ImportTaste** [ptrsuder/cloud-folder-browser#25]
From the error log:
`[2020-11-20 4:41:48 AM] Failed to load <https://thetrove.is/Assets/3D/Printing/Universal%20Tile/Universal%20Tile%20-%2028mm%20Terrain%20%3F40%20Pledge/>`

I think this is related to a bug with the site itself... notice the bottom left of this screenshot, I have the header highlighted in the top right.

![image](https://user-images.githubusercontent.com/53661808/99792899-67155880-2aed-11eb-9b20-af456fd4ce22.png)

The site SHOULD be converting that question mark to `%3F`, but it isn't. This only occurs in the header, all the other links to this directory work fine.

**Comment by ptrsuder** [comment]
Hm, it works fine for me.

**Comment by ImportTaste** [comment]
> Hm, it works fine for me.

The URL itself does, but I think the header going to an invalid URL causes a parsing error.

**Comment by ptrsuder** [comment]
I mean I don't get error.

**Comment by ImportTaste** [comment]
I think you're right, it seems to have been a fluke. If something fails to load, does it ever retry before moving on to the next thing? If it does retry, could you have the error log show each attempt? If it doesn't, could it?

**Comment by ptrsuder** [comment]
Eh, if some folder fails to load it most probably because of borked url, so retries will not help really. But maybe I'll add this, thanks. Will close this.
