### ISSUE TITLE
[BUG] JDownloader links always generate a error

### ISSUE THREAD

**Issue by guifa11** [ptrsuder/cloud-folder-browser#26]
**System:** Windows 10
**Cloud storage:** Sergen.Allsync, The Trove
**How to replicate the error:**
1- Click EDIT
2- ADD the link
3- Click compare folders content
4- Select the folder/files and click "Get Jdownloader links"
**Error:**
![image](https://user-images.githubusercontent.com/1879223/101822872-c113a780-3b08-11eb-9973-f90b318978a7.png)
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
YandexDiskSharp.DiskException: Ошибка проверки поля "public_key": Это поле является обязательным. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at YandexDiskSharp.Utilities.Extensions.GetJsonTextReader(HttpWebRequest request) in E:\Documents\GitHub\cloud-folder-browser\YandexDiskSharp\Utilities\Extensions.cs:line 13
   --- End of inner exception stack trace ---
   at YandexDiskSharp.Utilities.Extensions.GetJsonTextReader(HttpWebRequest request) in E:\Documents\GitHub\cloud-folder-browser\YandexDiskSharp\Utilities\Extensions.cs:line 21
   at YandexDiskSharp.RestClient.GetPublicResourceDownloadLink(String publicKey, String path) in E:\Documents\GitHub\cloud-folder-browser\YandexDiskSharp\RestClient.cs:line 716
   at CloudFolderBrowser.SyncFilesForm.CreateJdLinkcontainer() in E:\Documents\GitHub\cloud-folder-browser\CloudFolderBrowser\SyncFilesForm.cs:line 268
   at CloudFolderBrowser.SyncFilesForm.getJdLinks_button_Click(Object sender, EventArgs e) in E:\Documents\GitHub\cloud-folder-browser\CloudFolderBrowser\SyncFilesForm.cs:line 575
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
CloudFolderBrowser
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Baltras/Desktop/CloudFolderBrowser_0.9.10/CloudFolderBrowser_0.9.10%20-%20Copy/CloudFolderBrowser.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4290.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4210.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.1.22727
    CodeBase: file:///C:/Users/Baltras/Desktop/CloudFolderBrowser_0.9.10/CloudFolderBrowser_0.9.10%20-%20Copy/Newtonsoft.Json.DLL
----------------------------------------
Aga.Controls
    Assembly Version: 1.7.6.0
    Win32 Version: 1.7.6.0
    CodeBase: file:///C:/Users/Baltras/Desktop/CloudFolderBrowser_0.9.10/CloudFolderBrowser_0.9.10%20-%20Copy/Aga.Controls.DLL
----------------------------------------
YandexDiskSharp
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Baltras/Desktop/CloudFolderBrowser_0.9.10/CloudFolderBrowser_0.9.10%20-%20Copy/YandexDiskSharp.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4290.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
PortableSettingsProvider
    Assembly Version: 0.2.1.0
    Win32 Version: 0.2.1.0
    CodeBase: file:///C:/Users/Baltras/Desktop/CloudFolderBrowser_0.9.10/CloudFolderBrowser_0.9.10%20-%20Copy/PortableSettingsProvider.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4261.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4290.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
MegaApiClient
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Baltras/Desktop/CloudFolderBrowser_0.9.10/CloudFolderBrowser_0.9.10%20-%20Copy/MegaApiClient.DLL
----------------------------------------
HtmlAgilityPack
    Assembly Version: 1.8.6.0
    Win32 Version: 1.8.6
    CodeBase: file:///C:/Users/Baltras/Desktop/CloudFolderBrowser_0.9.10/CloudFolderBrowser_0.9.10%20-%20Copy/HtmlAgilityPack.DLL
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/Windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by ptrsuder** [comment]
Provided exception is for Yandex Disk. Can you provide url?

**Comment by guifa11** [comment]
I am not sure how i fixed this, but i stopped this error. I am using a private Allsync, and for some reason all the JDownloads are not working and if i try to download anything i get 7kb corrupted files.
