### ISSUE TITLE
0.9.10 - Check folder/Check all subfolders does not work

### ISSUE THREAD

**Issue by Meketh74** [ptrsuder/cloud-folder-browser#29]
Hi ptrsuder,

I am encountering two problems in v0.9.10:

1.) Right click context menu functions `Check all subfolders` and `Check folder` does not do anything for me in v0.9.10.
Having a working 'Check all subfolder' would be great, especially for deep folder structures. If I choose a fodler by mouse selection e.g. on top level it also only chooses this folder not the subfolders.
2.) Trying `flat list` did also not help, as Ctrl+A for selecting all does not work, I can only select one file via mouse click in right window. Multi selection is not possible.

Let me know if you need further info on the problem.

Thanks and best
Meketh

**Comment by ptrsuder** [comment]
Those context menu options are leftovers. 
You can check whole folder tree just fine. First click checks only folder with files, second one selects all subfolders.
