### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by joebywan** [ptrsuder/cloud-folder-browser#3]
I'm looking at it and I can't see an exe, bat, jar, py, anything I'm used to executing.

Is there something I'm missing? or is there a built binary somewhere?

**Comment by ptrsuder** [comment]
Are you downloading release or repository? 
![image](https://user-images.githubusercontent.com/18538582/59874439-e063c580-93a6-11e9-8fa3-19a698e12900.png)
