### ISSUE TITLE
Issue with Trove.is

### ISSUE THREAD

**Issue by Meketh74** [ptrsuder/cloud-folder-browser#30]
Hi ptrsuder,
unfortunately I am not able to parse thetrove.is.
- If I use https://thetrove.is/Books/ for parsing I get the error "too much data to load". 
- If I go a directory level below e.g. https://thetrove.is/Books/Dungeons%20%26%20Dragons%20%5Bmulti%5D/ I get a "Failed to parse web page" pop-up window.
Any chance for a fix?
Thanks for this awesome, very helpful project!
Meketh

**Comment by ptrsuder** [comment]
Some folders are just links to another folders (magazines mostly). I'll probably leave them as it is, but instead of message for every failed to load folder you will get list of them when loading is finished.
