### ISSUE TITLE
Unable to use resulting Link Container zip in jDownloader to download files.

### ISSUE THREAD

**Issue by rjbprime** [ptrsuder/cloud-folder-browser#4]
Tried generating a new zip file for fur different troves for jDownloader over the past week, at different times and days. Resulting zip imports into jDownloader, but when set to download, says file not found on server. Convert the imported links to a DLC file, use http://dcrypt.it/ convert back to text to download in a single directory, and the files are downloaded.

Exported links from CFB
[linkcollector1342.zip](https://github.com/ptrsuder/cloud-folder-browser/files/3337785/linkcollector1342.zip)

Same links exported from jDownloader after importing previous. Rename to D&D5e.dlc
[D&D5e.dlc.txt](https://github.com/ptrsuder/cloud-folder-browser/files/3337787/D.D5e.dlc.txt)

**Comment by ptrsuder** [comment]
I think I fixed it, try it out.

**Comment by rjbprime** [comment]
It's now working, thanks for the update.
