### ISSUE TITLE
No search bar

### ISSUE THREAD

**Issue by tafeilgh** [ptrsuder/cloud-folder-browser#43]
There was a search bar in the previous version, but it is not fully displayed in the latest version, even if the taskbar has been hidden.
Tried full screen mode, didn't work either
![full](https://github.com/ptrsuder/cloud-folder-browser/assets/100503528/36846d50-df05-4c98-a83b-e4c32501b874)
![10new](https://github.com/ptrsuder/cloud-folder-browser/assets/100503528/f34577ab-a04c-4ed1-812a-9028bbdcafde)
![9 15](https://github.com/ptrsuder/cloud-folder-browser/assets/100503528/819fcf9c-b891-4f50-9a3b-3974260a7b5d)

**Comment by ptrsuder** [comment]
Ehh, I'm not sure what's the cause is. Something to do with scaling probably
