### ISSUE TITLE
Poor handling of folders with dots in name

### ISSUE THREAD

**Issue by Kanareika** [ptrsuder/cloud-folder-browser#44]
Also, names containing other special characters may not be handled correctly. Example:
Program thinks these are "new" files that are not in the folder:

![image](https://github.com/ptrsuder/cloud-folder-browser/assets/10144329/98f2978d-714a-411c-9bb8-fb605559572e)

However, these files are present - with the same names and sizes:

![image](https://github.com/ptrsuder/cloud-folder-browser/assets/10144329/23b3505d-5bb8-4935-8bf8-500812f9f23e)

This is independent of hosting (MEGA or allsync), so the problem is probably somewhere in the code comparing available and existing files.

**Comment by ptrsuder** [comment]
You can see that folder names are actually different. Windows doesn't support trailing dot in folder names per se.
