### ISSUE TITLE
Qloud and Ampersand in name not working

### ISSUE THREAD

**Issue by devilisin** [ptrsuder/cloud-folder-browser#45]
Hello

Seems there's an download issue with qloud when a file or directory name has a ampersand ("&") - which is quite usual (maybe a character escape issue)
Download does not happen in that case, and following few attemps CFB has to be restarted to download anything (probably the DL queue/slots hanging). If I select a folder tree, it seems that a single file or directory name in the tree with an ampersand ("&") is enough to create the issue and nothing is downloaded. Excluding (if practical) within the tree the file or folders with an ampersand ("&") works as intended, all the files/folders are downloaded.

Obviously using 0.10.30.

Thanks in advance;Best

**Comment by devilisin** [comment]
Hello

Not very elegant but I propose to check the following fix:

`diff --git a/CloudFolderBrowser/Download/CommonDownload/CommonFileDownload.cs b/CloudFolderBrowser/Download/CommonDownload/CommonFileDownload.cs
--- CloudFolderBrowser/Download/CommonDownload/CommonFileDownload.cs
+++ CloudFolderBrowser/Download/CommonDownload/CommonFileDownload.cs
@@ -58,9 +58,9 @@
         }
 
         string EncodeWebUrl(string url)
         {
-            return url.Replace("#", "%23").Replace(",", "%2C").Replace("?", "%3F");
+            return url.Replace("#", "%23").Replace(",", "%2C").Replace("?", "%3F").Replace("&", "%26");
         }
 
         public async Task StartDownload()
         {
`

**Comment by ptrsuder** [comment]
I'll have to check if that doesn't break links for other services

**Comment by ptrsuder** [comment]
should be fixed
