### ISSUE TITLE
Failed Cloud/Local comparison for AllSync (MEGA works)

### ISSUE THREAD

**Issue by devilisin** [ptrsuder/cloud-folder-browser#46]
Hello,

**Version 10.0.31**

With 0.10.31 using "Compare folders content" : 
- It works for MEGA folders
- It fails for AllSync folders (not yet tested with qloud, but same issue expected).

**Behavior**
- Local folders/files are not matched with cloud folders/files
- All folders/files from the cloud folders are proposed for download in the "Download files" window (i.e. not just the list of new folders/files compared to the local sync as usual (and working with 0.10.30)

Thanks in advance.

Best Regards

**Comment by DanteFaustus** [comment]
I am also encountering the same issue

**Comment by DanteFaustus** [comment]
(On Allsync...)
