### ISSUE TITLE
New issue RE: Unable to use resulting Link Container zip in jDownloader to download files.

### ISSUE THREAD

**Issue by rjbprime** [ptrsuder/cloud-folder-browser#5]
This may be related to #4, not sure. Tried importing a new linkcontainer zip into jDownloader, and it doesn't seem to progress past reading the zip file. The zip has nearly 4k links, so i'm not sure if it has too many links.

[linkcollector8426.zip](https://github.com/ptrsuder/cloud-folder-browser/files/3417027/linkcollector8426.zip)

Could this be looked into?

**Comment by ptrsuder** [comment]
Hm, works fine for me.

**Comment by rjbprime** [comment]
Worked it out, seems that jDownloader didn't like the directory that it was saved into, "D&amp;D 3rd Party". Renaming said directory to remove the amp; enabled jDownloader to load the links.
