### ISSUE TITLE
& in a file name causes app to crash.

### ISSUE THREAD

**Issue by Conspiracy3015** [ptrsuder/cloud-folder-browser#6]
If a filename includes an & in it, it causes the program to throw an error and stops the creation of the linkcontainer.

**Comment by ptrsuder** [comment]
Can you provide an example of such link?

**Comment by Conspiracy3015** [comment]
https://cloud.allsync.com/s/idd8EzzZfwLEpbP

Is the link I'm trying to get files from.

**Comment by ptrsuder** [comment]
So, it's not '&' but ':' in main directory name. I want to improve some other things and make new release, may take some time.

**Comment by Conspiracy3015** [comment]
Didn't even notice the :
Thnk you.
