### ISSUE TITLE
Ver. 0.9.2 Mega Download & Maximum Downloads

### ISSUE THREAD

**Issue by rjbprime** [ptrsuder/cloud-folder-browser#9]
Using Ver. 0.9.2, trying to download from a Mega link, the Maximum Downloads selector is maxing out at 4, and limiting downloaded files to the first 4 downloaded. When having more than 4 files, it does not seem to continue afterwards, but restarting the download, asks to redownload those 4 files. Changing to any number less than 4 also results in the number of files asking to be overwritten to change to that number.

Should the Maximum Downloads be doing this, and limiting the total downloaded files? Or should it be downloading a set amount concurrently, where that set amount is what is chosen?

**Comment by ptrsuder** [comment]
This was strange, I'm remembering it wasn't like that, lol. Anyway, fixed in 0.9.3. And yeah, max number of concurrent downloads in 4.
